# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='flow',
            field=models.CharField(choices=[('negative', 'Source'), ('positive', 'Expenditure')], max_length=30),
        ),
    ]
