# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20170818_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expendituretransaction',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='incometransaction',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
