# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 13:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0007_auto_20170818_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_balance',
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
            },
        ),
        migrations.AlterField(
            model_name='expenditurecategory',
            name='image',
            field=models.ImageField(upload_to='images/expenditure_categories/'),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='image',
            field=models.ImageField(upload_to='images/income_categories/'),
        ),
    ]
