# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20170830_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenditurecategory',
            old_name='image',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='incomecategory',
            old_name='image',
            new_name='icon',
        ),
    ]
